name: autocaller
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  share_plus: ^10.1.4
  firebase_dynamic_links: ^6.1.3
  geolocator: ^13.0.2  # For fetching GPS location
  google_maps_flutter: ^2.10.1
  firebase_database: ^11.3.4
  firebase_messaging: ^15.2.5
  googleapis_auth: ^1.4.0
  flutter_local_notifications: ^19.0.0
  intl: ^0.20.2
  flutter_tts: ^4.2.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/9-removebg-preview.png
    - assets/logo.png
    - assets/Screenshot 2025-02-11 at 2.12.38 PM.png
    - assets/autoCallerLogoWithoutName.png

